apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-green
  labels:
    app: python-app
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
      version: green
  template:
    metadata:
      labels:
        app: python-app
        version: green
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: python-app
          image: jnelsendevsec0387f0d6.azurecr.io/python-app:v2 
          ports:
            - containerPort: 5000
